// <auto-generated />
using System;
using HRIS_Employee.Infrastructure.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRIS_Employee.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260524011437_RequirdEmployeeSchedule")]
    partial class RequirdEmployeeSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeStatusId");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.HasIndex("ScheduleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmployeeStatuses");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EndDayOffset")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleDays", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduleDay_DayOfWeek", "\"DayOfWeek\" BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ScheduleOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndDayOffset")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SpecificDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleOverrides");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ShiftAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustedById")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NewClockIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NewClockOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OldClockIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OldClockOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedById");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftAdjustments");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ShiftRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ClockIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ClockOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsFlag")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ShiftRecords", t =>
                        {
                            t.HasCheckConstraint("CK_ShiftRecord_Status", "\"Status\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.Employee", b =>
                {
                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.Schedule", "Schedule")
                        .WithMany("Employees")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeStatus");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ScheduleDay", b =>
                {
                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.Schedule", "Schedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ScheduleOverride", b =>
                {
                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.Schedule", "Schedule")
                        .WithMany("ScheduleOverrides")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ShiftAdjustment", b =>
                {
                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.Employee", "AdjustBy")
                        .WithMany("ShiftAdjustments")
                        .HasForeignKey("AdjustedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.ShiftRecord", "Shift")
                        .WithMany("ShiftAdjustments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustBy");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ShiftRecord", b =>
                {
                    b.HasOne("HRIS_Employee.Infrastructure.Persistence.Models.Employee", "Employee")
                        .WithMany("ShiftRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.Employee", b =>
                {
                    b.Navigation("ShiftAdjustments");

                    b.Navigation("ShiftRecords");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.Schedule", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("ScheduleDays");

                    b.Navigation("ScheduleOverrides");
                });

            modelBuilder.Entity("HRIS_Employee.Infrastructure.Persistence.Models.ShiftRecord", b =>
                {
                    b.Navigation("ShiftAdjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
